author: aklump
create_tags: patch
do_version_commit: true
git_root: .
master: main
patch_prefix: .
preserve_patch_zero: true
push_master: true
push_tags: true
remote: origin
version_file: loft_core_cypress_selector.info.yml
